### ISSUE TITLE
CocoaPods error for BlackberryDynamics Swift

### ISSUE THREAD

**Issue by DanyalNaveed** [blackberry/BlackBerry-Dynamics-iOS-Samples#28]
I am unable to install BlackberryDynamics pods and receiving following error. Kindly let me know what issue is this. File Attached
![Screenshot 2022-05-11 at 4 12 03 PM](https://user-images.githubusercontent.com/30923997/167836379-914cc932-014a-491f-ba37-a20401d2a778.png)

**Comment by ektown** [comment]
Hi @DanyalNaveed, it seems that there was an issue with CloudFlare as a similar issue has been raised: https://github.com/CocoaPods/CocoaPods/issues/11355. Could you try downloading again?

**Comment by DanyalNaveed** [comment]
Perfect it worked
