### ISSUE TITLE
Good SDK 3.1.0 integration with Xcode 8.3.2

### ISSUE THREAD

**Issue by manishbajo2008** [blackberry/BlackBerry-Dynamics-iOS-Samples#4]
I have installed xcode v8.3.2 and trying to integrate good sdk v3.1.0 but i am unable to do so.When I went through release notes I found that this latest version will not support to Xcode 8.3 and later versions.But one of my colleagues is able to use the latest version of good sdk with Xcode 8.3.1 without any issue.How can we resolve this?

**Comment by bthornton32** [comment]
Hi @manishbajo2008 ,
Please post this question in the community forum here: https://community.blackberry.com/community/gdn/resources/developer_community 
Thanks
Brent
