### ISSUE TITLE
cocospods suppoort

### ISSUE THREAD

**Issue by ElizaSapir** [blackberry/BlackBerry-Dynamics-iOS-Samples#8]
do you support cocoapods?

**Comment by ektown** [comment]
Hi Eliza, 

Thanks for checking out BlackBerry Open Source projects. The short answer is that the BlackBerry Dynamics SDKs are not available in CocoaPods today. However, we are considering to support in the future releases as one of the distribution option.

If you'd like to follow our SDKs more closely or have other questions, recommend checking out BlackBerry Developers Forum: https://developers.blackberry.com/us/en/community.html 

Happy Coding!
-EK
